### ISSUE TITLE
Browser debug tool

### ISSUE THREAD

**Issue by shuizhugeju** [DotNetExtension/BlazorDesktop#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

https://docs.microsoft.com/zh-cn/aspnet/core/blazor/hybrid/developer-tools?view=aspnetcore-6.0&pivots=windows
in here we can see
```
 builder.Services.AddBlazorWebViewDeveloperTools()
```

Is possible to support it.

### Additional context

![image](https://user-images.githubusercontent.com/9857219/167051689-6cdbebd1-3601-415c-b2ce-8dade12ca85d.png)

**Comment by andrewbabbittdev** [comment]
@shuizhugeju This should be pretty simple to add. You can technically already do this by adding a reference to the `Microsoft.AspNetCore.Components.WebView.Wp` package as its just a service collection extension method.

I'll make it simpler and go add a wrapper for it and integrate it into the templates.

**Comment by andrewbabbittdev** [comment]
@shuizhugeju 

Added in 65f441a5b2521e3a254b014692336a8eaa6ecca1

Packages have been released to Nuget as well as v1.1.0, feel free to pull the new version and start using it.
