### ISSUE TITLE
Non Windows Support

### ISSUE THREAD

**Issue by HuaFangYun** [DotNetExtension/BlazorDesktop#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Can this project only run on winsdk? I tried to run the exe file directly, but to no avail

**Comment by andrewbabbittdev** [comment]
Blazor Desktop only has support for Windows ATM, it relies on WPF in order to render anything.

There is the potential to do something for Mac with Maui, but I havent had a chance to play with Maui as of now.
