### ISSUE TITLE
Can't the generated exe file be opened by directly double-clicking?

### ISSUE THREAD

**Issue by HuaFangYun** [DotNetExtension/BlazorDesktop#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/user-attachments/assets/34dd5cc6-d186-4820-a2f5-a181e09d5c94)
I used a template to create a project. After the generation is completed, double-clicking the bin folder cannot be directly opened. It can be like winform or wpf. Can I directly double click the.exe file to open it directly? Or did I add less configuration information?

**Comment by andrewbabbittdev** [comment]
This is not a bug and is the same way all other web projects in ASP.NET function, you cant run the executable without copying at least the `wwwroot` folder into the executable directory. The bin contents is largely only for use when debugging or launching with VS / VS Code and it has the startup directory set to your project directory.

If you want to make a distributable build, you should use `dotnet publish -c Release` which will output all the appropriate assets into the publish directory.

More info on publishing apps can be found in the .NET Docs here: https://learn.microsoft.com/en-us/dotnet/core/deploying/
